### ISSUE TITLE
add netsniff-ng 0.6.1

### ISSUE THREAD

**Issue by jonschipp** [open-nsm/ContainNSM#35]
Add netsniff-ng 0.6.1 to the collection

**Comment by sturdyjon** [comment]
@jonschipp Ive been using this for a while. It seems dev has paused. Would you mind a few PRs to support new Versions of things like the above or Bro 2.5? I don't want to step on anyone's toes, but also want to find some way to give back to the community. 

Thanks for all your hard work!!!

**Comment by jonschipp** [comment]
Hey @sturdyjon, that would be absolutely awesome. PR's happily accepted, I would like to get back on this project once I have more free time but doesn't seem like any time soon. There's a bunch of tickets to improve things in the future. Let me know if you get stuck or have any questions.

**Comment by jon-the-dev** [comment]
@jonschipp Hey Jon, sent another PR across. @sturdyjon is my work account. Didn't realize I was signed in there earlier. More to come!
